
baseurl = "http://abualsamid.com"
#baseurl = "http://abualsamid-blog.s3-website-us-west-2.amazonaws.com"
title = "Born2Code musings"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
category = "categories"
languageCode = "en-us"
language = "en-EN"
relativeurls = true

copyright = " (c) 2016 Abualsamid"


#theme = "hyde-x"
theme = "bootstrap"

# Pagination
paginate = 10
paginatePath = "page"

SectionPagesMenu = "main"

# Enable Disqus integration
#disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "born2code"
    email = "ahmad@abualsamid.com"

[params]
  brand = "born2code"
  topline = "be good at getting better"
  footline = "code with <i class='fa fa-heart'></li>"
  twitter = "http://twitter.com/born2code"
  github = "https://github.com/abualsamid"
  gravatarHash = "6d7b273512b621013346a866d80ffd30"
  # theme = "theme-base-08"
