
baseurl = "http://abualsamid.com"
#baseurl = "http://abualsamid-blog.s3-website-us-west-2.amazonaws.com"
title = "Born2Code musings"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
category = "categories"
languageCode = "en-us"
language = "en-EN"
canonifyurls = true
relativeurls = true

copyright = " (c) 2016 Abualsamid"


theme = "hugo-bootstrap"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
#disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "born2code"
    email = "ahmad@abualsamid.com"

[params]
  brand = "born2code"
  footline = "code with <i class='fa fa-heart'></li>"
